const menu = {
    list() {
        return [
    {
        "backMenu":[
        ],
        "frontMenu":[
        ],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    },
    {
        "backMenu":[
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-activity",
                        "buttons":[
                            "查看"
                        ],
                        "menu":"通知公告",
                        "menuJump":"列表",
                        "tableName":"news"
                    }
                ],
                "menu":"通知公告"
            }
			,
			{
                "child":[
                    {
						"appFrontIcon":"cuIcon-form",
                        "buttons":[
                            "查看",
                        ],
                        "menu":"心理健康",
                        "menuJump":"列表",
                        "tableName":"xinlijiankang"
                    }
                ],
                "menu":"心理健康"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-favor",
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"心理健康收藏",
                        "menuJump":"列表",
                        "tableName":"xinlijiankangCollection"
                    }
                ],
                "menu":"心理健康收藏"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-evaluate",
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"心理健康留言",
                        "menuJump":"列表",
                        "tableName":"xinlijiankangLiuyan"
                    }
                ],
                "menu":"心理健康留言"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-message",
                        "buttons":[
                            "查看"
                        ],
                        "menu":"心理咨询",
                        "menuJump":"列表",
                        "tableName":"zhixunshiChat"
                    }
                ],
                "menu":"心理咨询"
            }
			,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-list",
                        "buttons":[
                            "查看"
                        ],
                        "menu":"在线评测",
                        "tableName":"exampaper"
                    },
                    {
						"appFrontIcon":"cuIcon-footprint",
                        "buttons":[
                            "查看"
                        ],
                        "menu":"评测记录",
                        "tableName":"examrecord"
                    }
                ],
                "menu":"考试管理"
            }
			,
			{
			    "child":[
			        {
						"appFrontIcon":"cuIcon-form",
			            "buttons":[
			                "查看",
			                "删除"
			            ],
			            "menu":"咨询师预约",
			            "menuJump":"列表",
			            "tableName":"zhixunshiYuyue"
			        }
			    ],
			    "menu":"咨询师预约"
			}
        ],
        "frontMenu":[
        ],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"是",
        "hasFrontRegister":"是",
        "roleName":"用户",
        "tableName":"yonghu"
    }
]

	}
}
export default menu;
